# Generated by Django 2.2.3 on 2020-12-22 01:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=20, unique=True, verbose_name='访问IP')),
                ('address', models.CharField(max_length=300, verbose_name='访问地址')),
                ('name', models.CharField(max_length=50, verbose_name='用户名')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('url', models.URLField(blank=True, null=True, verbose_name='网址')),
                ('first_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='第一次访问时间')),
                ('last_time', models.DateTimeField(blank=True, null=True, verbose_name='最近访问时间')),
                ('views', models.IntegerField(default=0, verbose_name='访问次数')),
            ],
        ),
        migrations.CreateModel(
            name='IP_reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='点赞时间')),
                ('ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userinfo.UserIP', verbose_name='关联IP')),
                ('like_reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comments.Reply', verbose_name='点赞的回复')),
            ],
            options={
                'verbose_name': '点赞回复',
                'verbose_name_plural': '点赞回复',
            },
        ),
        migrations.CreateModel(
            name='IP_post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='点赞时间')),
                ('first_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='第一次访问文章时间')),
                ('last_time', models.DateTimeField(verbose_name='最近访问文章时间')),
                ('views', models.IntegerField(default=0, verbose_name='访问文章次数')),
                ('ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userinfo.UserIP', verbose_name='关联IP')),
                ('like_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post', verbose_name='点赞文章')),
            ],
            options={
                'verbose_name': '文章访问情况',
                'verbose_name_plural': '文章访问情况',
            },
        ),
        migrations.CreateModel(
            name='IP_comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='点赞时间')),
                ('ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userinfo.UserIP', verbose_name='关联IP')),
                ('like_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comments.Comment', verbose_name='点赞的评论')),
            ],
            options={
                'verbose_name': '点赞评论',
                'verbose_name_plural': '点赞评论',
            },
        ),
    ]
