# Generated by Django 2.2.3 on 2020-12-22 01:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bigcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': '大类',
                'verbose_name_plural': '大类',
            },
        ),
        migrations.CreateModel(
            name='Blog_panel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='博客名称')),
                ('motto', models.CharField(max_length=100, verbose_name='铭言')),
                ('icon', models.URLField(verbose_name='浏览器小图')),
                ('apple_touch_icon', models.URLField(verbose_name='苹果图')),
                ('blog_photo', models.URLField(verbose_name='个人头像')),
                ('index_img', models.URLField(verbose_name='首页大图')),
                ('icp_img', models.URLField(verbose_name='徽标')),
                ('zfb_1', models.URLField(verbose_name='支付宝选项')),
                ('zfb_2', models.URLField(verbose_name='支付宝二维码')),
                ('wx_1', models.URLField(verbose_name='微信选项')),
                ('wx_2', models.URLField(verbose_name='微信二维码')),
                ('dmk_img', models.URLField(blank=True, verbose_name='代码块头部图')),
                ('h12_img', models.URLField(blank=True, verbose_name='代码块h1-h2')),
                ('h34_img', models.URLField(blank=True, verbose_name='代码块h3-h4')),
                ('h56_img', models.URLField(blank=True, verbose_name='代码块h5-h6')),
            ],
            options={
                'verbose_name': '博客自定义',
                'verbose_name_plural': '博客自定义',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bigcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.Bigcategory', verbose_name='大类')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
            },
        ),
        migrations.CreateModel(
            name='Copyright',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': '版权',
                'verbose_name_plural': '版权',
            },
        ),
        migrations.CreateModel(
            name='Onemenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=100, verbose_name='图标')),
                ('name', models.CharField(max_length=100, verbose_name='菜单名')),
                ('url', models.URLField(blank=True, verbose_name='网址')),
                ('show', models.BooleanField(verbose_name='是否显示子菜单')),
                ('z_width', models.IntegerField(default=100, verbose_name='子菜单宽度')),
                ('order_id', models.IntegerField(default=1, verbose_name='排序')),
            ],
            options={
                'verbose_name': '一级菜单',
                'verbose_name_plural': '一级菜单',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
            },
        ),
        migrations.CreateModel(
            name='Twomenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=100, verbose_name='图标')),
                ('name', models.CharField(max_length=100, verbose_name='菜单名')),
                ('url', models.URLField(blank=True, verbose_name='网址')),
                ('order_id', models.IntegerField(default=1, verbose_name='排序')),
                ('onemenu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Onemenu', verbose_name='关联')),
            ],
            options={
                'verbose_name': '二级菜单',
                'verbose_name_plural': '二级菜单',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='标题')),
                ('body', models.TextField(verbose_name='内容')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('modified_time', models.DateTimeField(verbose_name='修改时间')),
                ('excerpt', models.CharField(blank=True, max_length=200, verbose_name='摘要')),
                ('usr_name', models.CharField(default='燃烧吧小宇宙', max_length=70, verbose_name='作者')),
                ('copy_url', models.URLField(default='www.jcqmxm.com/blog/posts/', verbose_name='原文链接')),
                ('content_int', models.IntegerField(default=1)),
                ('views', models.PositiveIntegerField(default=0, editable=False)),
                ('img_url', models.URLField(verbose_name='图床网址')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Category', verbose_name='分类')),
                ('copyright', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.Copyright', verbose_name='版权')),
                ('tags', models.ManyToManyField(blank=True, to='blog.Tag', verbose_name='标签')),
            ],
        ),
    ]
