# Generated by Django 2.2.3 on 2020-12-22 01:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='用户名')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('url', models.URLField(blank=True, null=True, verbose_name='网址')),
                ('text', models.TextField(verbose_name='评论内容')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('good_count', models.IntegerField(db_column='gcount', default=0, verbose_name='好评数')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post', verbose_name='文章')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='用户名')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('url', models.URLField(blank=True, null=True, verbose_name='网址')),
                ('text', models.TextField(verbose_name='回复内容')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('good_count', models.IntegerField(db_column='gcount', default=0, verbose_name='好评数')),
                ('rep_com', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comments.Comment', verbose_name='回复')),
                ('reply_again', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='comments.Reply', verbose_name='子回复')),
            ],
            options={
                'verbose_name': '回复',
                'verbose_name_plural': '回复',
            },
        ),
    ]
